blueprint:
  name: MQTT_Tasmota_CarPresence
  description: Open garage door when car connects to Wi-Fi
  domain: automation
  input:
    light:
      name: Light
      description: "This is the switch the presence detection will trigger"
      selector:
        entity:
          domain: light
    car_presence:
      name: Car Presence
      description: "This switch is the car's connection to the MQTT broker"
      selector:
        entity:
          domain: switch
mode: single
trigger:
  - platform: state
    entity_id: !input car_presence
    to: 'on'
  - platform: state
    entity_id: !input car_presence
    to: 'unavailable'
    for:
      minutes: 1
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input car_presence
            state: 'on'
          - condition: state
            entity_id: !input light
            state: light.turn_off
        sequence:
          - service: light.turn_on
            entity_id: !input light
      - conditions:
          - condition: state
            entity_id: !input car_presence
            state: 'unavailable'
          - condition: state
            entity_id: !input light
            state: light.turn_on
        sequence:
          - service: light.turn_off
            entity_id: !input light
    default: []
